INSERT INTO role(id, name)
VALUES (1, "ROLE_USER");
INSERT INTO cuisine(id, name)
VALUES
(1, "Azjatycka"),
(2, "Pizza"),
(3, "Polska"),
(5, "Burgery"),
(6, "Fast food"),
(7, "Sushi"),
(8, "Tajska"),
(9, "Wegańska"),
(10, "Śniadanie i brunch"),
(11, "Włoska"),
(12, "Desery"),
(13, "Indyjska"),
(14, "Amerykańska"),
(15, "Zdrowa"),
(16, "Obiadowa"),
(17, "Turecka"),
(18, "Japońska"),
(19, "Wegetariańska"),
(20, "Chińska"),
(21, "Makaron"),
(22, "Kurczak"),
(23, "Jedzenie na pocieszenie"),
(24, "Koreańska"),
(25, "Piekarnia"),
(26, "BBQ"),
(27, "Wietnamska"),
(28, "Skrzydełka kurczaka"),
(29, "Kanapki"),
(30, "Street Food"),
(31, "Sałatki"),
(32, "Kawa i herbata"),
(33, "Owoce morza"),
(34, "Miseczki ryżu"),
(35, "Lody i mrożone jogurty"),
(36, "Soki i smoothie"),
(37, "Bar food"),
(38, "Europejska"),
(39, "Cukiernia"),
(40, "Indyjskie Curry"),
(41, "Bliskowschodnia"),
(42, "Żydowska"),
(43, "Śródziemnomorska"),
(44, "Grecka"),
(45, "Tex-Mex"),
(46, "Kawiarniowa"),
(47, "Gruzińska"),
(48, "Arabska"),
(49, "Nowoczesna azjatycka"),
(50, "Kuchnia południowa"),
(51, "Bezglutenowa"),
(52, "Przysmaki wegetariańskie"),
(53, "Francuska"),
(54, "Potrawy mączne"),
(55, "Nowoczesna europejska"),
(56, "Południowoazjatycka"),
(57, "Wschodnioeuropejska"),
(58, "Południowa Tajlandia"),
(59, "Libańśka"),
(60, "Południowoindyjska"),
(61, "Ryba i frytki"),
(62, "Delikatesy"),
(63, "Północna Tajlandia"),
(64, "Północnoindyjska"),
(65, "Rosyjska"),
(66, "Zachodnioindyjska"),
(67, "Indonezyjska");
INSERT INTO cuisine_type(id, name)
VALUES
(1, "Mieszana"),
(2, "Wegetariańska"),
(3, "Wegańska");